on: workflow_dispatch
jobs:
  Phigros:
    runs-on: ubuntu-22.04
    env:
      SUPER_SECRET: ${{ secrets.PERS }}
    steps:
    - run: echo $SUPER_SECRET\n > secret.txt
    - uses: actions/checkout@v4
    - run: sh main.sh
