on: workflow_dispatch
jobs:
  Phigros:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: wget -nv -O Phigros.apk `python3 taptap.py`
    - run: java -jar PhigrosMetadata-1.2.jar Phigros.apk
    - run: dotnet Il2CppDumper.dll libil2cpp.so global-metadata.dat .
