on:
  schedule:
  - cron: '5 9 * * *'
  workflow-dispatch:
jobs:
  Phigros:
    runs-on: ubuntu-22.04
    env:
      SUPER_SECRET: ${{ secrets.PERS }}
    steps:
    - run: |
        git config --global user.name '7aGiven'
        git config --global user.email 'a@gmail.com'
        git clone https://$SUPER_SECRET@github.com/7aGiven/PhigrosAction .
    - run: sh main.sh $SUPER_SECRET
